name: doc_appointment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-99.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins/Poppins-Regular.ttf 
        - asset: assets/Poppins/Poppins-Italic.ttf
          style: italic

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/color/colors.xml
